### ISSUE TITLE
getNeighbors returns empty neighbors

### ISSUE THREAD

**Issue by SelimTavukcuoglu** [ImSaikiran/Geohash#8]
Hello, Thx for your work ! 

But there are troubles with neighbors calculation...

Here a log from my app : 

`Geohash 'spgr' ([44.91,4.75]) : neighbors : {"North":"","East":"spgx","South":"spgq","West":"spgp","NorthEast":"","SouthEast":"spgw","SouthWest":"spgn","NorthWest":""}`

Doesn't seem possible. Can you check it and fix ?

**Comment by skthon** [comment]
Fixed in this PR #11
