### ISSUE TITLE
Deprecated curly braces

### ISSUE THREAD

**Issue by rezasazesh** [ImSaikiran/Geohash#9]
Please fix the issue below it happens on PHP 7.4

Array and string offset access syntax with curly braces is deprecated in <b>/home11/rezasaze/public_html/wooflyapp.com/vendor/saikiran/geohash/src/Geohash.php</b> on line <b>231</b><br />

**Comment by brasizza** [comment]
Same here .. just came to see if someone already had this.

**Comment by rezasazesh** [comment]
I had to downgraded to 7.1 because was easier than duplicating the code and had no particular reason to use 7.4. Is there a PR for this already?

**Comment by skthon** [comment]
#10 Merged. @brasizza Thanks for the PR
